[project]
name = "pycomicconverter"
version = "0.1.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pillow>=11.3.0",
    "pymupdf>=1.26.3",
]
