name: Test Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"

    - name: Install dependencies
      run: |
        uv sync --extra build

    - name: Test build process
      run: |
        uv run python src/build.py

    - name: Verify executables exist
      run: |
        ls -la dist/
        file dist/pycomicconverter-cli
        file dist/pycomicconverter-gui

    - name: Test CLI executable
      run: |
        ./dist/pycomicconverter-cli --help